export const IMAGES = {
  hero: 'https://picsum.photos/seed/talkstars-hero/1200/700',
  founder: 'https://picsum.photos/seed/talkstars-founder/400/400',
  courses: {
    basic: 'https://picsum.photos/seed/ts-course-basic/600/400',
    individual: 'https://picsum.photos/seed/ts-course-individual/600/400',
    advanced: 'https://picsum.photos/seed/ts-course-advanced/600/400',
    teachers: 'https://picsum.photos/seed/ts-course-teachers/600/400',
    grammar: 'https://picsum.photos/seed/ts-course-grammar/600/400',
    communication: 'https://picsum.photos/seed/ts-course-comm/600/400',
    personality: 'https://picsum.photos/seed/ts-course-personality/600/400',
    interview: 'https://picsum.photos/seed/ts-course-interview/600/400',
    membership: 'https://picsum.photos/seed/ts-course-membership/600/400',
  },
  testimonials: {
    rahul: 'https://picsum.photos/seed/ts-rahul/100/100',
    sunita: 'https://picsum.photos/seed/ts-sunita/100/100',
    arjun: 'https://picsum.photos/seed/ts-arjun/100/100',
    priya: 'https://picsum.photos/seed/ts-priya/100/100',
    amit: 'https://picsum.photos/seed/ts-amit/100/100',
    sneha: 'https://picsum.photos/seed/ts-sneha/100/100',
    vikram: 'https://picsum.photos/seed/ts-vikram/100/100',
  },
  about: 'https://picsum.photos/seed/talkstars-about/800/500',
  classroom: 'https://picsum.photos/seed/talkstars-class/800/500',
  og: 'https://picsum.photos/seed/talkstars-og/1200/630',
} as const
